version: "2.3"

services:
  assessment_ms:
    build:
      context: ./assessment_ms
    image: assessment_ms:1.0
    container_name: assessment_ms
    depends_on:
      db:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    ports:
      - "${ASSESSMENT_MS_HOST_PORT}:8000"
    volumes:
      - "${ASSESSMENT_MS_SOURCE}:/app"
      - ./.env:/env/.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
  
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: "rabbit"
    ports:
      - "${RABBITMQ_HOST_HTTP_API_PORT}:15672"
      - "${RABBITMQ_HOST_TCP_PORT}:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "${RABBITMQ_CONFIG}:/etc/rabbitmq/rabbitmq.config"
          
  moodle:
    image: 'bitnami/moodle:3'
    container_name: moodle
    environment:
      - "APACHE_HTTP_PORT_NUMBER=${MOODLE_APACHE_HTTP_PORT_NUMBER}"
      - "APACHE_HTTPS_PORT_NUMBER=${MOODLE_APACHE_HTTPS_PORT_NUMBER}"
      - "MOODLE_DATABASE_TYPE=${MOODLE_DATABASE_TYPE}"
      - "MOODLE_DATABASE_PORT_NUMBER=${MOODLE_DATABASE_PORT_NUMBER}"
      - "MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME}"
      - "MOODLE_DATABASE_USER=${APACHE_HTTP_PORT_NUMBER}"
      - "MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_TYPE}"
      - "MOODLE_EMAIL=${MOODLE_DATABASE_PORT_NUMBER}"
    ports:
      - "${MOODLE_HOST_HTTP_PORT}:${MOODLE_APACHE_HTTP_PORT_NUMBER}"
      - "${MOODLE_HOST_HTTPS_PORT}:${MOODLE_APACHE_HTTPS_PORT_NUMBER}"
    volumes:
      - '${MOODLEDATA_PERSISTANCE}:/bitnami'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
      
  db:
    image: mysql:5
    container_name: mysql
    volumes:
      - "${MYSQL_PERSISTANCE}:/var/lib/mysql"
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --innodb_file_format=barracuda
                --innodb_file_per_table=On
                --innodb_large_prefix=On
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 10s
      retries: 10
             
  cassandra:
    image: cassandra:2.1
    container_name: cassandra
    ports:
      - "${CASSANDRA_HOST_TCP_PORT}:9042"
    volumes:
      - ./storage/cassandra:/var/lib/cassandra
    healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10