# Generated by Django 2.2.15 on 2020-08-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
            ],
        ),
    ]
